name: Python Unittest

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
          pip install pytest

      - name: Run unit tests
        env:
          PYTHONPATH: test
        run: |
          pytest test/unit -v

